### ISSUE TITLE
Failing views test

### ISSUE THREAD

**Issue by joemull** [BirkbeckCTP/imports#81]
A views test is failing with the default test runner on Python 3.10 (`django_nose` does not support Django 3 or Python 3.10).

```shell
FAIL: test_export_stages (imports.tests.test_views.TestViews)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/joe/.virtualenvs/janeway/lib/python3.10/site-packages/django/test/utils.py", line 387, in inner
    return func(*args, **kwargs)
  File "/home/joe/git/janeway/src/plugins/imports/tests/test_views.py", line 75, in test_export_stages
    self.assertEqual(200, response.status_code)
AssertionError: 200 != 404
```

**Comment by joemull** [comment]
Lots of tests are now failing.

This probably means we need to update the tests to use the default test runner, not nose.

Refactoring the fixtures might help as well.
